### ISSUE TITLE
the link http://fb.joj.me has no bulging

### ISSUE THREAD

**Issue by j-v** [j-v/FaceBulge#5]
change link to working bulge or remove it?

**Comment by eljojo** [comment]
👍  updoot

**Comment by danielsnider** [comment]
a bulge never dies, issue resolved in my mind!

Daniel Snider ツ

**Comment by j-v** [comment]
A working bulge lives on at http://facebulge.jonvolkmar.com/

**Comment by danielsnider** [comment]
💖

Daniel Snider ツ

**Comment by eljojo** [comment]
> a bulge never dies
> A working bulge lives on!

Close your eyes, give me your hand, darlin'
Do you feel my heart beating
Do you understand
Do you feel the same
Am I only dreaming
Is this burning an eternal flame

**Comment by j-v** [comment]
For your bulge
![brulebulge2](https://user-images.githubusercontent.com/558633/33281162-263f0b9c-d359-11e7-9167-00466489a668.PNG)

![brulebulge1](https://user-images.githubusercontent.com/558633/33281153-1f4c1a1e-d359-11e7-9bb4-f3034d02b8cc.PNG)
